const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const dotenv = require('dotenv');
dotenv.config();
const app = express();
app.use(cors({ origin: process.env.CLIENT_URL || '*', credentials: true }));
app.use(express.json());
app.get('/', (req,res)=>res.json({message:'Smart Campus API running'}));
app.use('/api/auth', require('./routes/auth'));
app.use('/api/students', require('./routes/students'));
app.use('/api/courses', require('./routes/courses'));
app.use('/api/attendance', require('./routes/attendance'));
app.use('/api/marks', require('./routes/marks'));
const PORT = process.env.PORT || 5000;
mongoose.connect(process.env.MONGO_URI).then(()=>app.listen(PORT,()=>console.log(`Server running on ${PORT}`))).catch(err=>console.error(err));
